refactor(server): temp. disable most PR build steps
Signed-off-by: Luciano Nooijen <luciano@lucianonooijen.com>

diff --git a/.github/workflows/pr-server.yml b/.github/workflows/pr-server.yml
--- a/.github/workflows/pr-server.yml
+++ b/.github/workflows/pr-server.yml
@@ -28,33 +28,33 @@ jobs:
           go-version: '1.23'
       - name: Display Go version
         run: go version
-      - name: Bootstrap
-        run: make bootstrap
-      - name: Run build for all platforms
-        run: make build-all
-      - name: Run ci script
-        run: make ci
-      - name: Coverage report
-        uses: irongut/CodeCoverageSummary@v1.3.0
-        with:
-          filename: server/cobertura.xml
-          badge: true
-          fail_below_min: false
-          format: markdown
-          hide_branch_rate: false
-          hide_complexity: false
-          indicators: true
-          output: both
-      - name: Publish Test Report
-        uses: mikepenz/action-junit-report@v5
-        if: success() || failure() # always run even if the previous step fails
-        with:
-          report_paths: 'server/junit.xml'
-      - name: Add Coverage PR Comment
-        uses: marocchino/sticky-pull-request-comment@v2
-        with:
-          recreate: true
-          path: code-coverage-results.md
+      #      - name: Bootstrap
+      #        run: make bootstrap
+      #      - name: Run build for all platforms
+      #        run: make build-all
+      #      - name: Run ci script
+      #        run: make ci
+      #      - name: Coverage report
+      #        uses: irongut/CodeCoverageSummary@v1.3.0
+      #        with:
+      #          filename: server/cobertura.xml
+      #          badge: true
+      #          fail_below_min: false
+      #          format: markdown
+      #          hide_branch_rate: false
+      #          hide_complexity: false
+      #          indicators: true
+      #          output: both
+      #      - name: Publish Test Report
+      #        uses: mikepenz/action-junit-report@v5
+      #        if: success() || failure() # always run even if the previous step fails
+      #        with:
+      #          report_paths: 'server/junit.xml'
+      #      - name: Add Coverage PR Comment
+      #        uses: marocchino/sticky-pull-request-comment@v2
+      #        with:
+      #          recreate: true
+      #          path: code-coverage-results.md
 
       # TODO: Move to main-server.yml
       - name: Install doctl
